### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by chrismelzer**
Good evening,

As promised I took a stab at refactoring the code.  It's a start at getting it more object oriented to hopefully make it easier to extend.  This is the first pass so it is far from ideal and still really rough looking.  This should provide some ideas on how the code can be further simplified for future expansions.

Thanks!

### CODE REVIEW

**Comment by stilgar77** [comment]
Hi there, Chris...hope you're doing well.

I took a couple steps back and learned more about Classes and how a Python
program is supposed to fit together.  Once I did this, I went back and
looked and the changes you made to Fantasy Gladiator and I just want to say
THANK YOU!  Looking at how you arranged things really help me conceptualize
some of the fundamentals of OOP.  If you put something in terms of a
Fantasy RPG I can learn anything!  Anyway, thanks for continuing to open
doors for me in this direction.

I'm about halfway through The Three Body Problem and I'm really liking it.
The formations of soldiers acting as an computer was a definite highlight.
Yesterday was Nick's last day at WWT.  What a great guy...going to miss
him.  Hope all is well with you and you're happy/healthy.

Kind regards,

Dave

**Comment by chrismelzer** [comment]
No problem, I'm glad it was helpful!  I'm working on a fun little project
where I'm taking the possible pilots/ships/upgrades in the X-Wing
miniatures game and having a genetic algorithm chew over them to look for
novel combinations.  I had a friend beat me so bad, it made me scrap my
build but then get overwhelmed with the possible combinations, so hopefully
this will help. :P

I'm really glad you're still liking the book!  It's a blast, even though
it's a trilogy, I still felt satisfied by the ending.  The parts covering
the cultural revolution were brutal and really made it feel more real to me
than anything I had learned before.

I was sorry to see Nick leave but as I'm sure you knew he was looking far
before I started to.  His next gig seems really exciting and like enough of
a risk that it could have a huge payoff in terms of his happiness/life
goals, so I'm super pumped for him! :)

I'm doing really well thanks!  I'm starting at Experian on June 6th as a
senior security engineer.  So still a few more weeks to relax, read, and
code before getting back to work.  The job seems like exactly the kinds of
challenges I want to tackle, it already has a big security department so
lots of room to grow, and I know quite a few people over there who are
happy.  Taking some time off has been one of the best decisions I've made,
it's really helped to let me step back and take a look at what I want and
how to hopefully avoid burning out so early.

How's the dungeon generator coming along?  I was reading about some maze
solving/dungeon generation algorithms and thought of you (here
http://www.gamasutra.com/blogs/AAdonaac/20150903/252889/Procedural_Dungeon_Generation_Algorithm.php
and here http://pcg.wikidot.com/pcg-algorithm:dungeon-generation).  I
know you want to code everything yourself, but you can re-implement the
algorithm in Python from scratch if you'd like (instead of importing one of
the ones already out there).  I'd love to see what you have when you're
ready to share it! :)  I find procedural level creation crazy cool for some
reason.  I'll definitely be sharing my AI code when it's a little further
along (write now it's just a JSON file containing the cards/stats and a
script which can read it :P).

It was good hearing from you, thanks for reaching out!

Chris

**Comment by chrismelzer** [comment]
Hey Dave,

I've been playing some games lately that you may have heard of, but if not
they could be some good sources of inspiration for the games you've been
working on.  The reason I think they might be helpful is each of them show
a different approach to creating text based games.

The first two Candy Box http://candies.aniwey.net/ and Candy Box 2
http://candybox2.net/ both slowly reveal themselves.  If you don't feel
like playing them, you can find LetsPlays on YouTube like this one.
https://www.youtube.com/watch?v=X9nAnYnPknI

The other game I've been having fun with is Dwarf Fortress
http://www.bay12games.com/dwarves/.  If you haven't checked out DF in a
while, they now have a Legend Browser which allows you to explore the
histories generated by the game.

Just interesting to see the different options for text based games and
adding depth through simulation (ala DF) or through slowly revealing
complexities and surprising the player (ala Candy Box).

Hope all is going well!

Chris

**Comment by stilgar77** [comment]
Hi Chris,

Hope you're doing well and thanks for the recommendations.  I've been
working on combing all the working elements from Fantasy Gladiator and
Dinky Dungeon (a navigable map, a D&D like combat system, a D&D like
ability check system, random Hero stat generation and to be scaleable
enough easily add new elements.) into one game in which I try to be as
Object Oriented as possible.  So, I think I did it....it is far from done,
but I accomplished everything I wanted to and I'm ready to work on
something else.  It's called Cavern of the Kobold King.  Let me know what
you think...couldn't and wouldn't have done it with you.

Kind regards,

Dave

**Comment by stilgar77** [comment]
https://github.com/stilgar77/CotKK

**Comment by chrismelzer** [comment]
Hey Dave,

Sorry for the loooooong delayed reply, I was hoping to fork this code
before replying but I've been pretty busy with the new job.  I've also been
building a modular synth which has been a blast but taken away a lot of my
free time I'd otherwise spend on the computer (which is definitely a good
thing :P).

I love the game!  The sleeps between printing the text caused me to hear
the floppy drive crunching on my old Commodore in my head, the timing is
perfect for those old games loaded on 5 1/4 floppies.  I also really like
the interface, how it switches between combat and navigation really well,
it reminded me of the old Infocom games.

The code is muuuuch cleaner as well, hopefully that means it's easier to
add to and maintain.

I did have a few items I was planning on working on in the fork I didn't
get to:


   - "Print Stats" crashes to desktop for me (it says it's undefined but I
   haven't looked in the code to see if it's not defined or a typo issue)
   - The artwork isn't always displayed for enemies (not sure if this is
   intentional)
   - I like your approach of using functions since they're quick to wrap
   your head around and getting the game playable before starting to get
   bogged down in design/layout.  Now that you have the game playable, I was
   going to take a stab at converting some of the functions to classes.
   Targeting mostly code that repeats itself a lot, has lots of variables that
   could be abstracted in order to simplify things (pass rooms visited as a
   list of rooms rather than having variables for each room visited that you
   check), and areas where data and logic are mixed together (creating methods
   in the classes for setting/modifying variables, methods for returning
   random numbers, methods for returning information about the room/character,
   etc.) .  This would help cut down the lines of code further and simplify
   adding more features since changing one line would be less likely to have
   cascading side-effects.

These are all small points that really only matter if the projects start to
get bigger of course, the fact that the game is playable is the only
achievement that matters! :)

Have you been able to work on anything else or further tweaks?  It looks
like you haven't uploaded anything since we last spoke.  Just curious if
there are more games out there.

Thanks and hope all is well!

Chris

**Pull request merged**
